"""Execute first migration

Revision ID: cc49b6b03c5a
Revises: 
Create Date: 2021-11-04 17:34:07.032209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cc49b6b03c5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beachforecastlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_dt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_dt', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('beach', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('ocean', sa.String(), nullable=True),
    sa.Column('live_info', sa.JSON(), nullable=True),
    sa.Column('forecast_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beachforecastlist_beach'), 'beachforecastlist', ['beach'], unique=False)
    op.create_index(op.f('ix_beachforecastlist_id'), 'beachforecastlist', ['id'], unique=False)
    op.create_index(op.f('ix_beachforecastlist_ocean'), 'beachforecastlist', ['ocean'], unique=False)
    op.create_index(op.f('ix_beachforecastlist_region'), 'beachforecastlist', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_beachforecastlist_region'), table_name='beachforecastlist')
    op.drop_index(op.f('ix_beachforecastlist_ocean'), table_name='beachforecastlist')
    op.drop_index(op.f('ix_beachforecastlist_id'), table_name='beachforecastlist')
    op.drop_index(op.f('ix_beachforecastlist_beach'), table_name='beachforecastlist')
    op.drop_table('beachforecastlist')
    # ### end Alembic commands ###
